import React, { useMemo, useState } from 'react';
import * as Icon from 'lucide-react';
import * as XLSX from 'xlsx';
import { createCustomer, updateCustomer } from './customerService';

const Badge = ({ children, kind = 'green' }) => <span className={`badge ${kind}`}>{children}</span>;
const money = value => `৳${Number(value).toLocaleString('en-US')}`;

export default function CustomerModule({ records, saveCustomers, notify }) {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All');
  const [area, setArea] = useState('All');
  const [selected, setSelected] = useState(null);
  const [editing, setEditing] = useState(null);
  const [adding, setAdding] = useState(false);
  const filtered = useMemo(() => records.filter(c =>
    `${c.name} ${c.customerId} ${c.phone} ${c.package} ${c.area}`.toLowerCase().includes(query.toLowerCase()) &&
    (status === 'All' || c.status === status) && (area === 'All' || c.area === area)), [records, query, status, area]);
  const commit = (form, customer) => { const next = customer ? records.map(c => c.customerId === customer.customerId ? updateCustomer(customer, form) : c) : [...records, createCustomer(form)]; saveCustomers(next); setEditing(null); setAdding(false); notify(customer ? 'Customer updated successfully' : 'Customer added successfully'); };
  const toggle = customer => { saveCustomers(records.map(c => c.customerId === customer.customerId ? { ...c, status: c.status === 'Active' ? 'Inactive' : 'Active' } : c)); notify(`Customer ${customer.status === 'Active' ? 'deactivated' : 'activated'}`); };
  const importFile = event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = e => { try { const workbook = XLSX.read(e.target.result, { type: 'array' }); const rows = XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]], { defval: '' }); const imported = rows.map((row, index) => { const value = (...keys) => { const key = Object.keys(row).find(k => keys.includes(k.toLowerCase().replace(/[^a-z]/g, ''))); return key ? row[key] : ''; }; const packageValue = String(value('package','connection','connectionpackage') || '100').replace(/[^0-9]/g, '') || '100'; const id = value('customerid','userid') || `BRK-IMP-${String(index + 1).padStart(4, '0')}`; return { customerId: id, userId: value('userid') || id.replace('BRK', 'USR'), name: value('name','customername') || 'Imported customer', profilePhoto: `https://i.pravatar.cc/120?u=${id}`, phone: String(value('phone','phonenumber')), whatsapp: String(value('whatsapp','whatsappnumber') || value('phone','phonenumber')), email: value('email'), address: value('address'), package: `${packageValue} Mbps`, monthlyBill: Number(value('monthlybill','packageprice')) || (Number(packageValue) === 500 ? 1500 : Number(packageValue) === 200 ? 1000 : 700), connectionStartDate: value('connectionstartdate','connectiondate') || '', duration: value('duration') || 'New customer', status: value('status','accountstatus') || 'Active', dateOfBirth: value('dateofbirth','dob') || '', area: value('area','zone') || 'Unassigned', assignedStaff: value('assignedstaff','deliveryman','salesperson') || 'Unassigned', referral: { code: value('referralcode') || `BRISK-RF-${id}`, totalReferrals: Number(value('totalreferrals')) || 0, successfulReferrals: 0 }, loyaltyHistory: [], purchaseHistory: [] }; }); saveCustomers([...records, ...imported]); notify(`${imported.length} customer${imported.length === 1 ? '' : 's'} imported successfully`); } catch { notify('Could not import this file. Please check the columns and file type.'); } }; reader.readAsArrayBuffer(file); event.target.value = ''; };
  return <>
    {(adding || editing) && <CustomerForm customer={editing} close={() => { setAdding(false); setEditing(null); }} submit={commit} />}
    {selected && <CustomerProfile customer={selected} close={() => setSelected(null)} edit={() => { setSelected(null); setEditing(selected); }} />}
    <div className="toolbar"><div className="table-search"><Icon.Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by name, ID, phone..."/></div><select className="filter" value={status} onChange={e => setStatus(e.target.value)}><option>All</option><option>Active</option><option>Inactive</option></select><select className="filter" value={area} onChange={e => setArea(e.target.value)}><option>All</option>{[...new Set(records.map(c => c.area))].map(a => <option key={a}>{a}</option>)}</select><label className="filter import-button"><Icon.Upload size={15}/> Import CSV / Excel<input type="file" accept=".csv,.xlsx,.xls" onChange={importFile}/></label><button className="primary" onClick={() => setAdding(true)}><Icon.Plus size={15}/> Add customer</button><span className="results">Showing {filtered.length} of {records.length} customers</span></div>
    <section className="panel table-panel">{records.length ? <div className="table-wrap"><table><thead><tr>{['Customer ID','Customer name','Phone','Package','Monthly bill','Since','Duration','Area','Status','Actions'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(c => <tr key={c.customerId}><td><b className="id">{c.customerId}</b></td><td><button className="table-person" onClick={() => setSelected(c)}><img src={c.profilePhoto} alt=""/><b>{c.name}</b></button></td><td>{c.phone}</td><td>{c.package}</td><td>{money(c.monthlyBill)}</td><td>{c.connectionStartDate}</td><td>{c.duration}</td><td>{c.area}</td><td><Badge kind={c.status === 'Active' ? 'green' : 'orange'}>{c.status}</Badge></td><td><div className="row-actions"><button className="row-action" onClick={() => setSelected(c)} title="View"><Icon.Eye size={15}/></button><button className="row-action" onClick={() => setEditing(c)} title="Edit"><Icon.Pencil size={15}/></button><button className="row-action" onClick={() => toggle(c)} title="Activate/deactivate"><Icon.Power size={15}/></button></div></td></tr>)}</tbody></table></div> : <div className="loading">Loading customers from customer.json…</div>}<div className="pagination"><span>Rows per page <select><option>20</option><option>50</option></select></span><span>{filtered.length} matching customers</span></div></section>
  </>;
}

function CustomerForm({ customer, close, submit }) { const [form, setForm] = useState({ name: customer?.name || '', phone: customer?.phone || '', whatsapp: customer?.whatsapp || '', email: customer?.email || '', address: customer?.address || '', package: customer?.package?.split(' ')[0] || '100', connectionStartDate: customer?.connectionStartDate || '', dateOfBirth: customer?.dateOfBirth || '', area: customer?.area || '', assignedStaff: customer?.assignedStaff || '', status: customer?.status || 'Active' }); const set = e => setForm({ ...form, [e.target.name]: e.target.value }); return <div className="modal-backdrop"><form className="modal customer-form" onClick={e => e.stopPropagation()} onSubmit={e => { e.preventDefault(); submit(form, customer); }}><div className="modal-head"><div><span className="eyebrow">{customer ? 'EDIT RECORD' : 'NEW RECORD'}</span><h2>{customer ? 'Edit customer' : 'Add customer'}</h2></div><button type="button" className="close" onClick={close}><Icon.X size={18}/></button></div><div className="form-grid">{[['name','Name','text'],['phone','Phone number','text'],['whatsapp','WhatsApp number','text'],['email','Email','email'],['address','Address','text'],['area','Area / zone','text'],['connectionStartDate','Connection start date','date'],['dateOfBirth','Date of birth','date'],['assignedStaff','Assigned staff','text']].map(([name,label,type]) => <label key={name}>{label}<input name={name} type={type} value={form[name]} onChange={set} required={['name','phone','area'].includes(name)}/></label>)}<label>Package<select name="package" value={form.package} onChange={set}><option value="100">100 Mbps</option><option value="200">200 Mbps</option><option value="500">500 Mbps</option></select></label><label>Status<select name="status" value={form.status} onChange={set}><option>Active</option><option>Inactive</option></select></label></div><div className="modal-actions"><button type="button" className="filter" onClick={close}>Cancel</button><button type="submit" className="primary">{customer ? 'Save changes' : 'Add customer'} <Icon.Check size={15}/></button></div></form></div>; }

function CustomerProfile({ customer, close, edit }) { const communications = customer.communicationHistory || [{ channel: 'SMS', subject: 'Customer Appreciation', date: 'Aug 18, 2026', status: 'Delivered' }, { channel: 'WhatsApp', subject: 'Monthly service reminder', date: 'Aug 01, 2026', status: 'Read' }]; return <div className="modal-backdrop"><div className="profile-modal" onClick={e => e.stopPropagation()}><div className="profile-head"><div className="profile-title"><img src={customer.profilePhoto} alt=""/><div><span className="eyebrow">CUSTOMER PROFILE</span><h2>{customer.name}</h2><p>{customer.customerId} · {customer.userId} <Badge kind={customer.status === 'Active' ? 'green' : 'orange'}>{customer.status}</Badge></p></div></div><div><button className="primary" onClick={edit}><Icon.Pencil size={15}/> Edit</button><button className="close" onClick={close}><Icon.X size={18}/></button></div></div><div className="profile-grid">{[['Phone',customer.phone],['WhatsApp',customer.whatsapp],['Email',customer.email],['Address',customer.address],['Connection',customer.package],['Monthly bill',money(customer.monthlyBill)],['Start date',customer.connectionStartDate],['Duration',customer.duration],['Date of birth',customer.dateOfBirth],['Area / zone',customer.area],['Assigned staff',customer.assignedStaff],['Referral code',customer.referral?.code]].map(x => <div className="profile-field" key={x[0]}><span>{x[0]}</span><b>{x[1] || '—'}</b></div>)}</div><div className="profile-columns"><div><h3>Communication history</h3>{communications.map(x => <p key={x.date + x.channel}>{x.channel} · {x.subject}<br/><small>{x.date} · {x.status}</small></p>)}</div><div><h3>Referrals</h3><p>{customer.referral?.totalReferrals || 0} total · {customer.referral?.successfulReferrals || 0} successful</p></div><div><h3>Loyalty & rewards</h3>{customer.loyaltyHistory?.length ? customer.loyaltyHistory.map(x => <p key={x.title}>{x.title} · {x.status}</p>) : <p>No reward history yet</p>}</div><div><h3>eCommerce purchases</h3>{customer.purchaseHistory?.length ? customer.purchaseHistory.map(x => <p key={x.orderId}>{x.orderId} · {x.items} · {money(x.amount)}</p>) : <p>No purchases yet</p>}</div></div></div></div>; }
